Specify types for member of MeOS that weren't declared.
Or were declared with types (None) that didn't match the types on the
Derived classes.  The mypy errors were roughly:

error: "MEoS" has no attribute "rhoc"
error: "MEoS" has no attribute "_constants"
error: Incompatible types in assignment (expression has type
 "Dict[str, List[float]]", base class "MEoS" defined the type as "None")